version: '2'
.catalog:
    name: "DW Test Storage"
    version: "v0.0.1"
    description: "DW Shared Storage"
    questions:
     - variable: "CLIENT_SCALE"
       default: 1
       description: "Number of NFS client containers to scale up"
       label: "NFS clients scale"
       required: true
       type: "int"

services:
  test:
    scale: "${CLIENT_SCALE}"
    start_on_create: true
